### PR TITLE
Initial agones setup

### PR DESCRIPTION
**Pull request by muratozkan**
Setting up the foundations for agones integration. The goals are:
 - [x] Cargo build with Agones SDK
 - [x] Server docker images

### CODE REVIEW

**Comment by syllabix** [comment]
@muratozkan looks awesome!! let's go 🚀 

[ not a blocker ] I would like to move to the `tokio` runtime. both actix and actix web support it now, and considering our new async crates and explicit uses of tokio might be good to just lock it all in. I can add this as a quick follow up though - no need  to block this - wdyt?

**Comment by muratozkan** [comment]
sure, sounds like a good idea (considering we use `tokio` explicitly now) 👍 

There's little remaining to be done for this PR I guess - I will use the SDK to discover the port and use it in the container - and then we can merge. The docker build update is already there, `skaffold dev` updates the containers in about 30 secs.

**Comment by syllabix** [comment]
sounds good - looking forward to seeing this land

**Review by syllabix — APPROVED** [review]
🆗

**Pull request merged**
